name: Create Release

permissions:
  id-token: write
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      updateType:
        type: choice
        description: Version update type
        options:
          - patch
          - minor
          - major

jobs:
  Update_version:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
#          token: ${{ secrets.GH_BOT_TOKEN }}
      - run: git config --global user.email "ibly31productions@gmail.com"
      - run: git config --global user.name "William Connolly"

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Run version update
        run: npm version ${{ github.event.inputs.updateType }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Package build
        shell: bash
        run: |
          mkdir -p build
          VERSION=$(cat package.json | grep '"version"' | awk '{ print $2 }' | sed 's/[",]//g')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          zip -r -q "build/${VERSION}.zip" dist

      - name: Create Release
        run: gh release create ${{ env.VERSION }} ./build/${{ env.VERSION }}.zip --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Push version to master
        run: git push origin master && git push origin --follow-tags
