name: Create Release

permissions:
  id-token: write
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      updateType:
        type: choice
        description: Version update type
        options:
          - patch
          - minor
          - major

jobs:
  Update_version:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
#          token: ${{ secrets.GH_BOT_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Run version update
        run: npm version ${{ github.event.inputs.updateType }}

      - name: Push version to master
        run: git push origin master && git push origin --follow-tags

      - name: Install dependencies
        run: npm ci

      - name: Create Release
        run: gh release create ${{ env.TAG_CURRENT }} --generate-notes
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
